[tool.poetry]
name = "vt-workflow-create-sample"
version = "0.1.0"
description = "A workflow for creating new samples in Virtool."
authors = ["Jake Alexander", "Ian Boyes", "Blake Smith"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
virtool-workflow = {git = "https://github.com/virtool/virtool-workflow", rev = "develop"}

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
